Hl without distant
German-Immersive-Railroading-Community/GIRSignals pull request #127
Opened 2022-04-22 19:14 UTC by Uhutown

All should work with the Exit Signal.

2022-04-22 22:33 UTC, Jeronimo97 commented
- Sh1 on Hl without distant doesn't work with signalbox
- Some HL signalling issues with signal box system (see at test server)

2022-05-04 12:21 UTC, MrTroble requested changes

2022-05-04 12:21 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/signalbox/config/HVSignalConfig.java
> +                    HL.HL11_12);
Same goes here maybe make class variable

2022-05-04 12:21 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/signalbox/config/HVSignalConfig.java
> +                    KSMain.KS_ZS1, KSMain.KS_ZS7);
Make static class variable

2022-05-04 12:21 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/signalbox/config/KSSignalConfig.java
> +                    HL.HL11_12);
Make static

2022-05-06 20:49 UTC, Jeronimo97 approved these changes

2022-05-06 21:49 UTC, MrTroble approved these changes

2022-05-07 11:19 UTC, merged