bug fixes && feat: ZS3_PLATE intigrated to Interoperability
German-Immersive-Railroading-Community/GIRSignals pull request #129
Opened 2022-05-08 16:58 UTC by Uhutown

2022-05-08 17:37 UTC, MrTroble requested changes

2022-05-08 17:37 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/signalbox/config/HVSignalConfig.java
>              final Optional<HLLightbar> getlightbar = (Optional<HLLightbar>) next
Implement missing HV plate

2022-05-08 17:37 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/signalbox/config/KSSignalConfig.java
>              final boolean nexthl = next.getProperty(SignalHL.STOPSIGNAL).isPresent()
Implement missing KS Plates

2022-05-08 17:37 UTC, MrTroble commented on changelog.md
> +* bug fixes
```suggestion
* fix: various fixes
* fix: Missing KS on shunting path
```

2022-05-10 20:24 UTC, Jeronimo97 approved these changes

2022-05-10 20:33 UTC, MrTroble approved these changes

2022-05-10 20:34 UTC, merged