added Config-tests
German-Immersive-Railroading-Community/GIRSignals pull request #130
Opened 2022-06-16 15:40 UTC by Uhutown

2022-06-16 16:53 UTC, MrTroble requested changes

2022-06-16 16:53 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/guis/GuiSignalBox.java
> +            sortOptions.getObjFromID(id);
Bitte entfernen, da es noch nicht fertig implementiert ist

2022-06-16 16:53 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/tileentitys/SignalTileEnity.java
> +            setCustomName(compound.getString(CUSTOMNAME));
Hier fehlt noch die CUSTOMNAME Property die muss zur map hinzugefuegt werden

2022-06-17 08:53 UTC, MrTroble requested changes

2022-06-17 08:53 UTC, MrTroble commented on src/main/java/eu/gir/girsignals/blocks/Signal.java
> +        if (!playerIn.getHeldItemMainhand().getItem().equals(GIRItems.LINKING_TOOL)) {
Check if the signal is linkable or can have a custom name

2022-06-20 08:03 UTC, MrTroble requested changes
Sonst sehr guter und lesbarer code, gute tests, ergibt soweit alles Sinn.

2022-06-20 08:03 UTC, MrTroble commented on src/test/java/eu/gir/girsignals/test/GIRConfigtestKS.java
> +        final DummySignal dummySignal = signalBase.copy();
Unneeded copy

2022-06-20 08:03 UTC, MrTroble commented on src/test/java/eu/gir/girsignals/test/GIRConfigtestKS.java
> +        final DummySignal dummySignal = signalBase.copy();
Unneeded copy

2022-06-20 08:03 UTC, MrTroble commented on src/test/java/eu/gir/girsignals/test/GIRConfigtestKS.java
> +        final DummySignal dummySignal = signalBase.copy();
Unneeded copy

2022-06-20 08:03 UTC, MrTroble commented on src/test/java/eu/gir/girsignals/test/GIRConfigtestKS.java
> +    final KSSignalConfig config = KSSignalConfig.INSTANCE;
Visibility modifer
```suggestion
    private final KSSignalConfig config = KSSignalConfig.INSTANCE;
```

2022-06-20 08:03 UTC, MrTroble commented on src/test/java/eu/gir/girsignals/test/GIRConfigtestHV.java
> +    final HVSignalConfig config = HVSignalConfig.INSTANCE;
Visibility modifier
```suggestion
    private final HVSignalConfig config = HVSignalConfig.INSTANCE;
```

2022-06-20 13:03 UTC, Jeronimo97 commented on src/test/java/eu/gir/girsignals/test/GIRConfigtestHL.java
> +        configtestHL(HL.HL8_9, HLExit.HL2_3, HLDistant.HL7, HLLightbar.GREEN, HL.HL11_12,
Das macht keinen Sinn

2022-06-20 13:03 UTC, Jeronimo97 commented on src/test/java/eu/gir/girsignals/test/GIRConfigtestHL.java
> +                HLExit.HL2_3, HLDistant.HL7, HLLightbar.OFF, 10);
Das macht keinen Sinn

2022-06-22 13:13 UTC, merged