Port/1.16.5
German-Immersive-Railroading-Community/GIRSignals pull request #171
Opened 2023-05-12 17:01 UTC by Jeronimo97

2023-05-16 20:14 UTC, MrTroble requested changes, later dismissed

2023-05-16 20:14 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/core/OSMapEntry.java
> +package com.troblecodings.signals.core;
Unneccessary use Maps.immutableEntryfrom guava https://guava.dev/releases/23.0/api/docs/com/google/common/collect/Maps.html

2023-05-16 21:24 UTC, Jeronimo97 commented on src/main/java/com/troblecodings/signals/core/OSMapEntry.java
> +package com.troblecodings.signals.core;
removed class

2023-05-17 06:32 UTC, Uhutown approved these changes

2023-05-17 08:48 UTC, merged