Feats UI/1.18
German-Immersive-Railroading-Community/GIRSignals pull request #212
Opened 2023-08-15 16:37 UTC by Uhutown

2023-08-16 20:20 UTC, MrTroble requested changes
Also das ist wild ich lese mir das nicht weiter durch bis die typen korrektheit wieder herrgestellt wird

2023-08-16 20:20 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/blocks/Signal.java
> +                    if (valuePack.predicate.test(properties)) {
Das macht keinen sinn. Es gibt kein Grund das zu detypsieren ausser man war zu faul einen anderen bug zu fixen. Warum der branch was passiert wenn der branch nicht mehr eintritt.

2023-08-16 20:20 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/blocks/Signal.java
> +                final BooleanProperty bool = (BooleanProperty) pack;
Selbes hier siehe oben

2023-08-16 20:20 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/core/SignalProperties.java
> +    public final List<Object> redstoneOutputs;
Warum die detypisierung? Das macht keinen sinn was sind die faelle die hier abgedeckt werden muessen

2023-08-16 20:20 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/properties/BooleanProperty.java
>  }
Das kann keiner Lesen, Was ist das ziel dieser Klasse(n)? Wenn das predicat true ist wird der wert applied oder was? Mit was wird das predicate gechecked? Warum sind das alles seperate Klassen? Bitte generics benutzen und die Predicate typisieren bitte

2023-08-18 15:57 UTC, Uhutown commented on src/main/java/com/troblecodings/signals/blocks/Signal.java
> +            if (properties.containsKey(pack.property) || pack.predicate.test(properties)) {
Ich glaube nicht das "properties.containsKey(pack.property)" als Bedingung reicht das ein RS Ouput kommt. Man sollte noch gucken das die Property "true" ist. Bitte aber vorher und nachher testen.

2023-08-19 17:37 UTC, MrTroble commented
Circle texture update from @Skywalkervalle was included into this PR as it was declared a bug fix please test @Jeronimo97

2023-08-19 18:23 UTC, Jeronimo97 commented
> Circle texture update from @Skywalkervalle was included into this PR as it was declared a bug fix please test @Jeronimo97

Won't work, I'll fix it later

2023-08-31 15:46 UTC, Jeronimo97 approved these changes

2023-09-20 17:27 UTC, MrTroble requested changes

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/ContainerPlacementtool.java
getInfo should be cached and

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/ContainerSignalBox.java
getInfo local cache

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/ContainerSignalController.java
getinfo local cache

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/GuiSignalBox.java
> +    public static final float[] ALL_LINES = getLines();
Why is this line cache public now? Access should be limited as the contents might be invalidated

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/GuiSignalBox.java
> +        this.entity.findRecursive(UIColor.class).stream().filter(
Yeah so this should be done differently if we are honest

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/NamableContainer.java
getInfo should be localy cached

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/handler/ClientNameHandler.java
> +            return new String(CLIENT_NAMES.getOrDefault(info, ""));
Why is there a string copy? Strings are immutable

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/handler/ClientSignalStateHandler.java
> +            return CURRENTLY_LOADED_STATES.getOrDefault(info, new HashMap<>());
Why was this changed unneccessary hash map allocation on all accesses

2023-09-20 17:27 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/signalbox/SignalBoxPathway.java
> +    private boolean checkReverseReset(final BlockPos pos) {
What is this trying to achieve?

2023-09-20 17:49 UTC, Uhutown commented on src/main/java/com/troblecodings/signals/guis/ContainerPlacementtool.java
It's getting chached in the SuperClass ContainerBase. Why should we chache it two times?

2023-09-20 17:49 UTC, Uhutown commented on src/main/java/com/troblecodings/signals/guis/ContainerSignalBox.java
The same as abow

2023-09-20 17:49 UTC, Uhutown commented on src/main/java/com/troblecodings/signals/guis/ContainerSignalController.java
The same

2023-09-20 17:49 UTC, Uhutown commented on src/main/java/com/troblecodings/signals/guis/GuiSignalBox.java
> +        this.entity.findRecursive(UIColor.class).stream().filter(
How?

2023-09-20 17:50 UTC, Uhutown commented on src/main/java/com/troblecodings/signals/handler/ClientNameHandler.java
> +            return new String(CLIENT_NAMES.getOrDefault(info, ""));
Ok I wasn't if this is so

2023-09-20 17:50 UTC, Uhutown commented on src/main/java/com/troblecodings/signals/signalbox/SignalBoxPathway.java
> +    private boolean checkReverseReset(final BlockPos pos) {
This is for the revers pathway reset.

2023-09-20 18:00 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/ContainerPlacementtool.java
1. No the function call it self is not it is still entering into a function call every time. Means function call overhead in EVERY line
2. If you need to change things it makes it harder. What if you make the function more complex? Even only by accident?

2023-09-20 18:01 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/guis/GuiSignalBox.java
> +        this.entity.findRecursive(UIColor.class).stream().filter(
Cache the UIColors for example idk thing of something

2023-09-20 18:02 UTC, MrTroble commented on src/main/java/com/troblecodings/signals/signalbox/SignalBoxPathway.java
> +    private boolean checkReverseReset(final BlockPos pos) {
Yeah I can read but what is this doing and why are we in linear time here what exactly do you mean by **reverse** reset

2023-09-24 18:42 UTC, MrTroble approved these changes

2023-09-24 18:45 UTC, merged